In [1]:
from scipy import sparse
import numpy as np

In [2]:
eye = np.eye(4)
print("Numpy 배열:\n", eye)

Numpy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
sapase_matrix = sparse.csr_matrix(eye)
print